In [1]:
import pandas as pd
import numpy as np
# --- Tabela 1: autorzy ---
autorzy = pd.DataFrame({
 'autor_id': [1, 2, 3, 4, 5, 6, 7, 8],
 'imie': ['Olga', 'Stanisław', 'Andrzej', 'Wisława', 'Ryszard',
 'Dorota', 'Szczepan', 'Jacek'],
 'nazwisko': ['Tokarczuk', 'Lem', 'Sapkowski', 'Szymborska', 'Kapuściński',
 'Masłowska', 'Twardoch', 'Dehnel'],
 'kraj': ['Polska', 'Polska', 'Polska', 'Polska', 'Polska',
 'Polska', 'Polska', 'Polska'],
 'nagrody': ['Nobel', 'SFF', 'SFF', 'Nobel', 'Reporter',
 'Polityka', 'NIKE', 'NIKE']
})
# --- Tabela 2: książki ---
ksiazki = pd.DataFrame({
 'ksiazka_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112],
 'autor_id': [1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 7, 8],
 'tytul': ['Księgi Jakubowe', 'Bieguni', 'Solaris', 'Cyberiada',
 'Wiedźmin', 'Narrenturm', 'Wiersze wybrane', 'Podróże z Herodotem',
 'Wojna polsko-ruska', 'Morfina', 'Król', 'Lala'],
 'kategoria': ['historyczna', 'obyczajowa', 'sci-fi', 'sci-fi',
 'fantasy', 'fantasy', 'poezja', 'reportaz',
 'obyczajowa', 'historyczna', 'historyczna', 'obyczajowa'],
 'cena': [79.90, 49.00, 39.00, 42.00, 45.00, 55.00, 35.00,
 52.00, 38.00, 48.00, 59.00, 44.00],
 'strony': [912, 376, 198, 295, 320, 512, 180, 263, 153, 618, 688, 432]
})
# --- Tabela 3: zamówienia ---
np.random.seed(2026)
n = 80
zamowienia = pd.DataFrame({
 'zam_id': range(5001, 5001 + n),
 'ksiazka_id': np.random.choice(ksiazki['ksiazka_id'], size=n),
 'ilosc': np.random.randint(1, 6, size=n),
 'data': pd.to_datetime('2026-01-01') +
pd.to_timedelta(np.random.randint(0, 120, n), unit='D'),
 'kanal': np.random.choice(['web', 'aplikacja', 'telefon'], size=n, p=
[0.6, 0.3, 0.1]),
 'miasto': np.random.choice(['Warszawa', 'Kraków', 'Wrocław', 'Gdańsk',
'Poznań'], size=n)
})
print(f"Autorzy: {autorzy.shape}")
print(f"Ksiazki: {ksiazki.shape}")
print(f"Zamowienia: {zamowienia.shape}")

Autorzy: (8, 5)
Ksiazki: (12, 6)
Zamowienia: (80, 6)

### Ćwiczenie 1
merge() - łączenie dwóch tabel

In [5]:
print(ksiazki)
print(autorzy)
ksiazki_z_autorami = ksiazki.merge(autorzy, on='autor_id')
print(f"Shape: {ksiazki_z_autorami.shape}")
ksiazki_z_autorami.head()

    ksiazka_id  autor_id                tytul    kategoria  cena  strony
0          101         1      Księgi Jakubowe  historyczna  79.9     912
1          102         1              Bieguni   obyczajowa  49.0     376
2          103         2              Solaris       sci-fi  39.0     198
3          104         2            Cyberiada       sci-fi  42.0     295
4          105         3             Wiedźmin      fantasy  45.0     320
5          106         3           Narrenturm      fantasy  55.0     512
6          107         4      Wiersze wybrane       poezja  35.0     180
7          108         5  Podróże z Herodotem     reportaz  52.0     263
8          109         6   Wojna polsko-ruska   obyczajowa  38.0     153
9          110         7              Morfina  historyczna  48.0     618
10         111         7                 Król  historyczna  59.0     688
11         112         8                 Lala   obyczajowa  44.0     432
   autor_id       imie     nazwisko    kraj   nagrody
0         1       Olga    Tokarczuk  Polska     Nobel
1         2  Stanisław          Lem  Polska       SFF
2         3    Andrzej    Sapkowski  Polska       SFF
3         4    Wisława   Szymborska  Polska     Nobel
4         5    Ryszard  Kapuściński  Polska  Reporter
5         6     Dorota    Masłowska  Polska  Polityka
6         7   Szczepan     Twardoch  Polska      NIKE
7         8      Jacek       Dehnel  Polska      NIKE
Shape: (12, 10)

,ksiazka_id,autor_id,tytul,kategoria,cena,strony,imie,nazwisko,kraj,nagrody
0,101,1,Księgi Jakubowe,historyczna,79.9,912,Olga,Tokarczuk,Polska,Nobel
1,102,1,Bieguni,obyczajowa,49.0,376,Olga,Tokarczuk,Polska,Nobel
2,103,2,Solaris,sci-fi,39.0,198,Stanisław,Lem,Polska,SFF
3,104,2,Cyberiada,sci-fi,42.0,295,Stanisław,Lem,Polska,SFF
4,105,3,Wiedźmin,fantasy,45.0,320,Andrzej,Sapkowski,Polska,SFF

Wynik ma 12 wierszy
Wynik ma 10 kolumn
Nowe kolumny: imie, nazwisko, kraj, nagrody

In [6]:
ksiazki_test = pd.concat([
 ksiazki,
 pd.DataFrame({'ksiazka_id':[999], 'autor_id':[999],
 'tytul':['Ksiazka bez autora'], 'kategoria':['test'],
 'cena':[30.0], 'strony':[100]})
], ignore_index=True)

In [8]:
inner = ksiazki_test.merge(autorzy, on='autor_id', how='inner')
left = ksiazki_test.merge(autorzy, on='autor_id', how='left')
right = ksiazki_test.merge(autorzy, on='autor_id', how='right')
outer = ksiazki_test.merge(autorzy, on='autor_id', how='outer')

print(f'inner: {inner.shape[0]} wierszy')
print(f'left: {left.shape[0]} wierszy')
print(f'right: {right.shape[0]} wierszy')
print(f'outer: {outer.shape[0]} wierszy')

inner: 12 wierszy
left: 13 wierszy
right: 12 wierszy
outer: 13 wierszy

In [9]:
audyt = ksiazki_test.merge(autorzy, on='autor_id', how='outer', indicator=True)
audyt['_merge'].value_counts()

_merge
both          12
left_only      1
right_only     0
Name: count, dtype: int64

Inner ma mniej wierszy niż left, bo pokazuje tylko te książki, które mają pasującego autora w obu tabelach.

### Ćwiczenie 2
Merge łańcuchowy i kolumny wyliczane

In [ ]:
pelne = (
 zamowienia
 .merge(ksiazki, on='ksiazka_id')
 .merge(autorzy, on='autor_id')
)
print(f"Pelna tabela: {pelne.shape}")
pelne.head()

Pelna tabela: (80, 15)

,zam_id,ksiazka_id,ilosc,data,kanal,miasto,autor_id,tytul,kategoria,cena,strony,imie,nazwisko,kraj,nagrody
0,5001,102,5,2026-04-05,web,Poznań,1,Bieguni,obyczajowa,49.0,376,Olga,Tokarczuk,Polska,Nobel
1,5002,107,2,2026-02-08,web,Poznań,4,Wiersze wybrane,poezja,35.0,180,Wisława,Szymborska,Polska,Nobel
2,5003,111,1,2026-04-19,web,Poznań,7,Król,historyczna,59.0,688,Szczepan,Twardoch,Polska,NIKE
3,5004,109,4,2026-02-24,web,Warszawa,6,Wojna polsko-ruska,obyczajowa,38.0,153,Dorota,Masłowska,Polska,Polityka
4,5005,105,2,2026-01-10,web,Warszawa,3,Wiedźmin,fantasy,45.0,320,Andrzej,Sapkowski,Polska,SFF

In [6]:
# 1. Wartość zamówienia
pelne['wartosc'] = pelne['ilosc'] * pelne['cena']
# 2. Miesiąc zamówienia
pelne['miesiac'] = pelne['data'].dt.month
# 3. Pełne imię i nazwisko autora
pelne['autor_pelne'] = pelne['imie'] + ' ' + pelne['nazwisko']
# 4. Kategoria cenowa książki
pelne['kategoria_cenowa'] = np.where(pelne['cena'] >= 50, 'droga', 'tania')

In [8]:
print(f'Wszystkich zamówień jest {pelne.shape[0]}')
print(f'Łączny przychód to {pelne['wartosc'].sum()}')
print(f'Średnia wartość zamówienia: {pelne['wartosc'].mean().round(2)}')
print(f'Unikalnych książek sprzedało się {pelne['tytul'].nunique()}')

Wszystkich zamówień jest 80
Łączny przychód to 11963.8
Średnia wartość zamówienia: 149.55
Unikalnych książek sprzedało się 12

### Ćwiczenie 3
groupby i .agg() - raporty per kategoria

In [ ]:
print(pelne.groupby('kategoria')['wartosc'].sum().sort_values(ascending=False))
print(pelne.groupby('kategoria')['wartosc'].agg(['count', 'mean', 'sum']).round(2))

kategoria
historyczna    4136.8
sci-fi         2334.0
obyczajowa     1999.0
fantasy        1930.0
reportaz       1144.0
poezja          420.0
Name: wartosc, dtype: float64
             count    mean     sum
kategoria
fantasy         14  137.86  1930.0
historyczna     22  188.04  4136.8
obyczajowa      17  117.59  1999.0
poezja           7   60.00   420.0
reportaz         5  228.80  1144.0
sci-fi          15  155.60  2334.0

In [24]:
pelne.groupby('autor_pelne').agg(
liczba_zamowien=('zam_id', 'count'),
laczna_sprzedaz=('wartosc', 'sum'),
sredni_ilosc=('ilosc', 'mean')
).round(2).sort_values('laczna_sprzedaz', ascending=False)

                     liczba_zamowien  laczna_sprzedaz  sredni_ilosc
autor_pelne
Olga Tokarczuk                    18           3389.8          2.72
Stanisław Lem                     15           2334.0          3.80
Andrzej Sapkowski                 14           1930.0          2.86
Szczepan Twardoch                 11           1580.0          2.91
Ryszard Kapuściński                5           1144.0          4.40
Jacek Dehnel                       5            748.0          3.40
Wisława Szymborska                 7            420.0          1.71
Dorota Masłowska                   5            418.0          2.20

In [27]:
print(pelne.groupby(['kategoria', 'kanal'])['wartosc'].sum())

kategoria    kanal
fantasy      aplikacja     475.0
             telefon       225.0
             web          1230.0
historyczna  aplikacja    1988.5
             telefon       527.4
             web          1620.9
obyczajowa   aplikacja     586.0
             telefon       136.0
             web          1277.0
poezja       aplikacja      70.0
             telefon        70.0
             web           280.0
reportaz     aplikacja     416.0
             telefon       260.0
             web           468.0
sci-fi       aplikacja     534.0
             telefon       279.0
             web          1521.0
Name: wartosc, dtype: float64

In [29]:
pelne['wartosc_kat'] = pelne.groupby('kategoria')['wartosc'].transform('sum')
pelne['udzial_w_kategorii_pct'] = (pelne['wartosc'] / pelne['wartosc_kat'] * 100).round(2)
print(pelne.groupby('kategoria')['udzial_w_kategorii_pct'].sum())

kategoria
fantasy         99.98
historyczna    100.00
obyczajowa      99.98
poezja         100.00
reportaz       100.01
sci-fi         100.00
Name: udzial_w_kategorii_pct, dtype: float64

### Ćwiczenie 4
pivot_table i crosstab - raport biznesowy

In [33]:
pd.pivot_table(pelne, index='kategoria', columns='miesiac', values='wartosc', aggfunc='sum', fill_value=0)

miesiac           1       2      3      4
kategoria
fantasy       595.0   410.0  270.0  655.0
historyczna  1342.5  1790.9  634.4  369.0
obyczajowa    301.0   623.0  274.0  801.0
poezja        105.0    70.0  140.0  105.0
reportaz      416.0     0.0  728.0    0.0
sci-fi        765.0   615.0  672.0  282.0

In [32]:
pd.pivot_table(pelne, index='kategoria', columns='miesiac', values='wartosc', aggfunc='sum', fill_value=0, margins=True, margins_name='RAZEM')

miesiac           1       2       3       4    RAZEM
kategoria
fantasy       595.0   410.0   270.0   655.0   1930.0
historyczna  1342.5  1790.9   634.4   369.0   4136.8
obyczajowa    301.0   623.0   274.0   801.0   1999.0
poezja        105.0    70.0   140.0   105.0    420.0
reportaz      416.0     0.0   728.0     0.0   1144.0
sci-fi        765.0   615.0   672.0   282.0   2334.0
RAZEM        3524.5  3508.9  2718.4  2212.0  11963.8

In [34]:
pd.crosstab(pelne['kanal'], pelne['miasto'])

miasto     Gdańsk  Kraków  Poznań  Warszawa  Wrocław
kanal
aplikacja       7       1       5         6        4
telefon         1       4       1         3        2
web             5       9      14         9        9

In [35]:
pd.crosstab(pelne['kanal'], pelne['miasto'], normalize='index') * 100

miasto        Gdańsk     Kraków     Poznań   Warszawa    Wrocław
kanal
aplikacja  30.434783   4.347826  21.739130  26.086957  17.391304
telefon     9.090909  36.363636   9.090909  27.272727  18.181818
web        10.869565  19.565217  30.434783  19.565217  19.565217

In [9]:
print(pelne)

    zam_id  ksiazka_id  ilosc       data      kanal    miasto  autor_id  \
0     5001         102      5 2026-04-05        web    Poznań         1
1     5002         107      2 2026-02-08        web    Poznań         4
2     5003         111      1 2026-04-19        web    Poznań         7
3     5004         109      4 2026-02-24        web  Warszawa         6
4     5005         105      2 2026-01-10        web  Warszawa         3
..     ...         ...    ...        ...        ...       ...       ...
75    5076         105      2 2026-04-20  aplikacja   Wrocław         3
76    5077         104      2 2026-03-20    telefon    Kraków         2
77    5078         104      1 2026-02-20        web  Warszawa         2
78    5079         103      4 2026-01-27        web    Kraków         2
79    5080         110      4 2026-02-21        web  Warszawa         7

                 tytul    kategoria  cena  strony       imie    nazwisko  \
0              Bieguni   obyczajowa  49.0     376       Olga   Tokarczuk
1      Wiersze wybrane       poezja  35.0     180    Wisława  Szymborska
2                 Król  historyczna  59.0     688   Szczepan    Twardoch
3   Wojna polsko-ruska   obyczajowa  38.0     153     Dorota   Masłowska
4             Wiedźmin      fantasy  45.0     320    Andrzej   Sapkowski
..                 ...          ...   ...     ...        ...         ...
75            Wiedźmin      fantasy  45.0     320    Andrzej   Sapkowski
76           Cyberiada       sci-fi  42.0     295  Stanisław         Lem
77           Cyberiada       sci-fi  42.0     295  Stanisław         Lem
78             Solaris       sci-fi  39.0     198  Stanisław         Lem
79             Morfina  historyczna  48.0     618   Szczepan    Twardoch

      kraj   nagrody  wartosc  miesiac         autor_pelne kategoria_cenowa
0   Polska     Nobel    245.0        4      Olga Tokarczuk            tania
1   Polska     Nobel     70.0        2  Wisława Szymborska            tania
2   Polska      NIKE     59.0        4   Szczepan Twardoch            droga
3   Polska  Polityka    152.0        2    Dorota Masłowska            tania
4   Polska       SFF     90.0        1   Andrzej Sapkowski            tania
..     ...       ...      ...      ...                 ...              ...
75  Polska       SFF     90.0        4   Andrzej Sapkowski            tania
76  Polska       SFF     84.0        3       Stanisław Lem            tania
77  Polska       SFF     42.0        2       Stanisław Lem            tania
78  Polska       SFF    156.0        1       Stanisław Lem            tania
79  Polska      NIKE    192.0        2   Szczepan Twardoch            tania

[80 rows x 19 columns]

Największy przychód przynosiły książki historyczne, szczególnie w 2. miesiącu, gdzie sprzedaż była najwyższa. Dobrze sprzedawały się też kategorie sci-fi i fantasy, co pokazuje, że klienci regularnie wybierali te typy książek. Zdecydowanie najwięcej zamówień pochodziło z kanału web, zwłaszcza w Poznaniu i Warszawie, dlatego sprzedaż internetowa jest najważniejszym kanałem dla firmy.